Serrurier/urls.py
from django.urls import path
from . import  views
from django.contrib.auth import views as auth_views

app_name = 'Serrurier'

urlpatterns=[
  path('',views.home,name='home'),
  path('change_language/<str:lang>/', views.change_language, name='change_language'),
  # path('mail', views.create_view, name='create_view'),
  path('login/', auth_views.LoginView.as_view(), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('register/', views.register_view, name='register'),
  path('soumettre_avis/', views.soumettre_avis, name='soumettre_avis'),
  path('services/', views.service, name='services'),
  path('contact/', views.contact_view, name='contact'),
  path('admin_contact', views.admin_contact, name='admin_contact'),

  



]

SerurierProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('Serrurier.urls'))
]

Serrurier/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
RATING_CHOICES = [(i, i) for i in range(1, 5)]
class Avis(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    commentaire = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)

    def __str__(self):
        return f'Avis de {self.user}'
    


class Contact(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    message = models.TextField()

    def __str__(self):
        return f"Message from {self.full_name}"

Serrurier/forms.py
from django import forms
from .models import Avis, Contact
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class AvisForm(forms.ModelForm):
    class Meta:
        model = Avis
        fields = ['commentaire', 'rating']


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'email', 'phone_number', 'message']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control','rows': 6}),
        }

Serrurier/views.py
from django.shortcuts import redirect, render

from django.http import HttpResponse

from django.shortcuts import render

from datetime import datetime
from Serrurier import models

from Serrurier.models import Avis

from .utils import send_email_with_html_body

from .models import Avis, Contact
from .forms import AvisForm, ContactForm, UserRegisterForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.urls import reverse

class CustomLoginView(LoginView):
    template_name = 'registration/login.html'  


def register_view(request):
    lang = request.session.get('lang', 'fr')
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Envoyer l'email de bienvenue
            subject = "Bienvenue sur Notre Site"
            template = f'mail/welcome_email_{lang}.html'
            context = {
                'date': datetime.today().date(),
                'username': user.username,
                'email': user.email
            }
            receivers = [user.email]
            send_email_with_html_body(
                subjet=subject,
                receivers=receivers,
                template=template,
                context=context
            )
            # Connecter l'utilisateur directement après l'inscription
            login(request, user)
            messages.success(request, 'compte crée avec succès!')
            return redirect('Serrurier:home')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


def contact_view(request):
    lang = request.session.get('lang', 'fr')
    template_name = f"accueil/contact_{lang}.html"

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Vous devez enregistrer le formulaire avant d'envoyer l'email pour avoir accès aux données sauvegardées
            contact = form.save()

            # Envoyer un email de confirmation au client
            subject_client = "Confirmation de réception de votre message"
            template_client = 'mail/confirmation_email_client.html'
            context_client = {
                'full_name': contact.full_name,  # Utilisez l'instance sauvegardée pour récupérer le nom complet
                'date': datetime.today().date(),

            }
            send_email_with_html_body(
                subjet=subject_client,
                receivers=[contact.email],  # Utilisez l'instance sauvegardée pour récupérer l'email
                template=template_client,
                context=context_client
            )

            # Envoyer un email de notification au gérant
            subject_manager = "Nouvelle demande de contact"
            template_manager = 'mail/notification_email_manager.html'
            context_manager = {
                'full_name': contact.full_name,  # Utilisez l'instance sauvegardée pour récupérer les données
                'email': contact.email,
                'phone_number': contact.phone_number,
                'message': contact.message,
                'date': datetime.today().date(),
            }
            send_email_with_html_body(
                subjet=subject_manager,
                receivers=['rochdi53sami@gmail.com'],
                template=template_manager,
                context=context_manager
            )

            messages.success(request, 'Votre demande a été envoyé avec succès!')
            # Rediriger vers une page de succès après l'envoi des emails
            return redirect('Serrurier:home')

    else:
        form = ContactForm()

    return render(request, template_name, {'form': form})


def home(request):
    lang = request.session.get('lang', 'fr')
    avis_list = Avis.objects.all()    
    template_name = f"accueil/home_{lang}.html"
    return render(request, template_name, {'avis_list': avis_list})


def service(request):
    lang = request.session.get('lang', 'fr')
    template_name = f"accueil/services_{lang}.html"

    return render(request,template_name)

@login_required
def soumettre_avis(request):
    lang = request.session.get('lang', 'fr')
    template_name = f"avis/AvisForm_{lang}.html"

    if request.method == 'POST' and request.user.is_authenticated:
        # if avis:  # If an avis already exists
        #     form = AvisForm(request.POST, instance=avis)
        # else:
        form = AvisForm(request.POST)
        
        if form.is_valid():
            avis = form.save(commit=False)
            avis.user = request.user
            avis.save()
            messages.success(request, 'Votre Avis a été envoyé avec succès!')
            return redirect('Serrurier:home')
    else:
        form = AvisForm()
    return render(request, template_name, {'form': form})



def create_view(request, *args, **kwargs):
    """ This view help to create and account for testing sending mails."""
    cxt = {}
    if request.method == "POST":
        email = request.POST.get('email')
        print(email)
        subjet = "Test Email"
        template = 'mail/email.html'
        context = {
            'date': datetime.today().date,
            'email': email
        }

        receivers = [email]

        has_send = send_email_with_html_body(
            subjet=subjet,
            receivers=receivers,
            template=template,
            context=context
            )

        if has_send:
           cxt =  {"msg":"mail envoyee avec success."}
        else:
            cxt = {'msg':'email envoie echoue.'}

    return render(request, 'index.html', cxt)       


@staff_member_required  # Ceci garantit que seul un utilisateur staff (admin) peut accéder à cette vue
def admin_contact(request):
    contacts = Contact.objects.all()  # Récupérer toutes les demandes de contact
    return render(request, 'admin/contact_requests.html', {'contacts': contacts})


def change_language(request, lang):
    request.session['lang'] = lang
    return redirect(request.META.get('HTTP_REFERER', reverse('Serrurier:home')))

Serrurier/templates/accueil/home_ab.html
{% extends "base_ab.html" %}
{% load static %}

{% block content %}
	<div class="header">
		<div>
			<h1>الصناعة المفتوحة</h1>
			<p>
				لا يمكننا أن نكون آمنين دائمًا من مشكلة تتعلق بنظام القفل في سيارتك. كل شيء على ما يرام، ثم في يوم ما تفقد مفاتيحك، أو تتعطل قفل الباب، أو لا يستجيب نظام الأمان الإلكتروني بالمزيد... ماذا يجب عليك فعله في هذا الوقت؟
				لا تقلق! في TAI Cles، نحن هنا لمساعدتك ونستخدم خبرتنا لحل مشكلاتك في نظام القفل السياري بسرعة. يقوم أخصائيو الأقفال لدينا بالتدخل بفعالية لإصلاح مشاكلك.
			</p>
		</div>
	</div>

	<div class="content"></div>

	<section id="md-reassurance" class="pt-1 py-5">
		<h2 class="text-center uniform-rounded">4 أسباب جيدة لاختيار TAI Cles</h2>
		<div class="scroll scroll-bar px-1 px-md-0">
			<div class=" container px-0 min-w-400">
				<div class="row justify-content-lg-center">
					<div class="col-sm-3 p-3 my-2 me-2 rounded-big d-flex flex-column effect-style-dark-shadow md-reassurance-item">
						<img class="" src="{% static 'images/devis.png' %}" width="70" height="70" alt="أيقونة الاقتباس مجاني دائمًا">
						<div class="separator-reassurance md-secondary"></div>
						<span style="font-weight:bold;">احصل دائمًا على اقتباس مجاني</span>
						<p class="mt-2">لا توجد تكاليف خفية. احصل على اقتباس واضح قبل أي تدخل.</p>
					</div>

					<div class="col-sm-3 p-3 my-2 me-2 rounded-big d-flex flex-column effect-style-dark-shadow md-reassurance-item">
						<img class="" src="{% static 'images/fourchette_prix.png' %}" width="70" height="70" alt="أيقونة نطاق الأسعار معروفة قبل الطلب">
						<div class="separator-reassurance md-dark-blue"></div>
						<span class="bold">
							نطاق الأسعار معروف قبل الطلب
						</span>
						<p class="mt-2">تعرّف على التكلفة المحتملة قبل تأكيد طلبك.</p>
					</div>

					<!-- Card 3 -->
					<div class="col-sm-3 p-3 my-2 me-2 rounded-big d-flex flex-column effect-style-dark-shadow md-reassurance-item">
						<img class="" src="{% static 'images/satisfaction.png' %}" width="70" height="70" alt="أيقونة عملاء راضون دائمًا">
						<div class="separator-reassurance md-primary"></div>
						<span class="bold">
							عملاء راضون دائمًا
						</span>
						<p class="mt-2">أولويتنا هي رضاء عملائنا. اكتشف شهادات عملائنا الراضين.</p>
					</div>

					<!-- Card 4 -->
					<div class="col-sm-3 p-3 my-2 rounded-big d-flex flex-column effect-style-dark-shadow md-reassurance-item">
						<img class="" src="{% static 'images/reseau.png' %}" width="70" height="70" alt="أيقونة التدخل على مدار 24 ساعة طوال أيام الأسبوع">
						<div class="separator-reassurance md-right"></div>
						<span class="bold">
							شبكة من المحترفين المؤهلين
						</span>
						<p class="mt-2">فريقنا مكون من محترفين ذوي خبرة وثقة، تم اختيارهم بعناية.</p>
					</div>
				</div>
			</div>
		</div>
	</section>

</div>
</div>
<div class="content">
    <h2>اكتشف موقعنا</h2>
</div>
<div id="map" style="width: 100%; height: 400px;"></div>

<div class="content">
    <p>
        تقع محلنا في قلب المدينة النابضة بالحياة، مما يوفر تجربة فريدة لجميع زبائننا. تكشف الخريطة التفاعلية أدناه عن موقع محلنا بدقة. ندعوك بحرارة لزيارتنا واستكشاف الحلول المخصصة التي نقدمها في مجال الأقفال السيارية، كل ذلك في جو ودود واحترافي.
    </p>
</div>
<h3 class="review-title">ما يقوله عملاؤنا عنا</h3>

<div class="reviews-section">

    {% for avis in avis_list %}
        <div class="review-card">
            <div class="review-header">
                <span class="review-author">{{ avis.user.username }}</span>
                <span class="review-date">{{ avis.date | date:"d M Y" }}</span>  <!-- تنسيق التاريخ -->
            </div>
            <div class="review-body">
                <p>{{ avis.commentaire }}</p>
            </div>
            <div class="review-rating">
                {% for i in "12345" %}
                    {% if forloop.counter <= avis.rating %}
                        <i class="fas fa-star"></i>
                    {% else %}
                        <i class="far fa-star"></i>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endfor %}
	
</div>
<form class="form-button" action="{% url 'Serrurier:soumettre_avis' %}">
	<button class="btn btn-info" type="submit">أضف تقييمًا أيضًا!</button>
 </form>

 <form class="form-button" action="{% url 'Serrurier:services' %}">
	<button class="btn btn-info" id="fixedButton" type="submit">الوصول إلى خدماتنا</button>
 </form>

<style>



	#fixedButton {
		position: fixed;       /* Permet de fixer le bouton sur l'écran */
		bottom: 20px;          /* Distance depuis le bas de l'écran */
		right: 20px;           /* Distance depuis le côté droit de l'écran */
		z-index: 999;          /* Assure que le bouton est au-dessus des autres éléments */
		padding: 10px 20px;    /* Espacement intérieur pour le bouton */
		background-color: #243846; /* Couleur de fond du bouton */
		color: white;          /* Couleur du texte du bouton */
		border: none;          /* Supprime la bordure */
		border-radius: 5px;    /* Arrondit les coins */
		cursor: pointer;       /* Change le curseur en main lors du survol */
		transition: background-color 0.3s; /* Transition douce pour le survol */
	}
	
	#fixedButton:hover {
		background-color: #56d2f4; /* Change la couleur de fond lors du survol */
	}
	
	* {
		margin: 0;
		padding: 0;
	}
	.body {
		height: 300vh;
	}
	.header {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 400px;
		width: 100%;
		background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url("/static/images/banniere.png");
		background-size: cover;
		background-position: center;
		background-repeat: no-repeat;
		background-attachment: fixed;
		color: aliceblue;

	}

	.header h1 {
		font-size: 2.5em;
		margin-bottom: 10px;
	}
	.header p {
		font-size: 1.2em;
		max-width: 800px; /* Limiter la largeur du texte pour une meilleure lisibilité */
		margin: 0 auto; /* Centrer le paragraphe */
	}
	.content {
		padding: 40px;
	}
	.separator-reassurance {
		height: 8px;
		width: 15%;
		border-radius: 30px;
		margin: 10px 0; /* Ajoute un peu d'espace au-dessus et en dessous du séparateur */
	}
	.md-secondary {
		background-color: #fea652; /* Noir, mais vous pouvez choisir la couleur que vous préférez */

	}
	.md-dark-blue {
		background-color: #243846
	}
	.md-primary {
		background-color: #56d2f4
	}
	.md-right {
		background-color: #cbced0
	}

	.md-reassurance-item {
		box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1), 0 6px 20px rgba(0, 0, 0, 0.05); /* Add this line */
		transition: transform 0.2s, box-shadow 0.2s; /* Smooth transition for hover effect */
		margin: 0 10px 20px; /* Espacement autour de chaque card */
		border-radius: 20px; /* Arrondissement des coins */
		min-height: 250px;
		max-width: 250px;

	}

	.md-reassurance-item:hover {
		transform: translateY(-5px); /* Lifts the card up slightly when hovered for a more dynamic effect */
		box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2), 0 8px 24px rgba(0, 0, 0, 0.1); /* Slightly larger shadow on hover */
	}
	.md-reassurance-item p {
		margin-top: 10px;
		font-size: 1em;
		color: #333; /* Changez cette couleur selon le thème de votre site */
	}

	.md-reassurance-section {
		margin-top: 20px;  /* Ajoutez une marge au-dessus de la section */
	}

	.content-title {
		text-align: center;  /* Centrez le titre */
	}

	/* Styles pour les cartes d'avis */
	.card {
		width: 100%; /* Utilisez toute la largeur disponible */
		margin-bottom: 20px;
		border: 1px solid #e0e0e0;
		border-radius: 10px;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
		transition: transform 0.2s, box-shadow 0.2s;
		background-color: #f9f9f9; /* Couleur de fond légère */
	}
	
	.fa-star {
		font-size: 1.2em; /* Augmentez la taille des étoiles */
		color: #FFD700; /* Utilisez une couleur d'or riche */
	}
	.form-button {
		background-color: #f4f4f4;
		padding: 40px;
		text-align: right;
		padding-top:0 ;
	  }

	.reviews-section {
		background-color: #f4f4f4;
		padding: 40px;
		text-align: center;
	  }
	  .review-title {
		font-size: 2em;
		margin-bottom: 30px;
		font-weight: 300;
		color: #333;
	  }
	  .review-card {
		background-color: #fff;
		border: 1px solid #e0e0e0;
		border-radius: 10px;
		padding: 20px;
		margin: 10px auto;
		width: 80%;
		max-width: 600px;
		transition: transform 0.2s, box-shadow 0.2s;
	  }
	  .review-card:hover {
		transform: translateY(-5px);
		box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.1);
	  }
	  .review-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		border-bottom: 1px solid #eee;
		padding-bottom: 10px;
		margin-bottom: 15px;
	  }
	  .review-author {
		font-weight: 500;
		font-size: 1.1em;
	  }
	  .review-date {
		font-size: 0.9em;
		color: #888;
	  }
	  .review-body {
		font-size: 1em;
		line-height: 1.6;
		color: #555;
	  }
	  .review-rating {
		margin-top: 15px;
	  }
	  .fas, .far {
		color: #FFD700;
	  }
	  .far {
		opacity: 0.5;
	  }
	  .reviews-section {
		display: flex;
		flex-wrap: wrap;
		justify-content: space-around;
		padding: 40px;
		background-color: #f4f4f4;
	  }
	  .review-card {
		width: calc(33.333% - 20px);
		margin: 10px;
		box-sizing: border-box;
	  }
		/* Responsive design */
@media (max-width: 900px) {
.review-card {
  width: calc(50% - 20px);
}
}
@media (max-width: 600px) {
.review-card {
  width: 100%;
}
}
	

/* Styles pour l'emplacement sur la carte */
#map {
width: 100%;
height: 400px;
margin-top: 20px;
border-radius: 10px;
box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}



</style>

<script>
    var map = L.map('map').setView([33.562020, -7.560824], 13); // Initialiser la carte sur les coordonnées fournies

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a>',
        maxZoom: 19
    }).addTo(map);

    L.marker([33.562020, -7.560824]).addTo(map) // Ajouter un marqueur sur les coordonnées fournies
        .bindPopup('Votre position ou celle de votre entreprise.').openPopup();
</script>
{% endblock %}

Serrurier/templates/accueil/services_ab.html
{% extends 'base_ab.html' %}
{% load static %}
{% block css %}
	{{ block.super }}
	<style>
		.service-section {
			padding: 40px 0;
		}

		.service-card {
			background-color: #f8f9fa;
			border: none;
			border-radius: 10px;
			padding: 20px;
			margin-bottom: 30px;
			transition: transform 0.2s ease-in-out;
		}

		.service-card:hover {
			transform: translateY(-10px);
		}

		.service-icon {
			font-size: 2rem;
			color: #011520;
		}

		.service-title {
			font-size: 1.5rem;
			font-weight: bold;
			margin-top: 10px;
			margin-bottom: 10px;
		}

		.service-description {
			color: #6c757d;
		}
		.cta-button {
			background-color: #56d2f4;
			color: #fff;
			border: none;
			border-radius: 5px;
			padding: 10px 20px;
			text-align: center;
			text-decoration: none;
			display: inline-block;
			font-size: 16px;
			margin: 15px 2px;
			transition-duration: 0.4s;
			cursor: pointer;
		}

		.cta-button:hover {
			background-color: #fff;
			color: #011520;
		}
		.cta-section {
			text-align: center;
			padding: 40px 0;
		}

		.certification-section {
			text-align: center;
			padding: 40px 0;
		}

		.certification-text {
			margin-bottom: 30px;
			font-size: 1.1rem;
			color: #6c757d;
		}

		.certification-image {
			max-width: 80%;
			margin-bottom: 10px;
		}
		
		.service-section-title {
			text-align: center;
			font-size: 2rem;
			margin-bottom: 20px;
		}

		.certification-image {
			max-width: 80%;
			max-height: 200px; /* Set the maximum height as needed */
			margin-bottom: 10px;
		}
	</style>

{% endblock %}

{% block content %}
<section class="container my-5 pt-5">
    <h2 class="service-section-title">خدماتنا</h2>
    <div class="row">
        <div class="col-lg-4 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">نسخ المفاتيح</h5>
                    <p class="card-text">نسخ المفاتيح لجميع العلامات التجارية والطرازات، بما في ذلك المفاتيح التقليدية والمفاتيح الذكية.</p>
                </div>
            </div>
        </div>

        <div class="col-lg-4 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">تغيير برمجة المفاتيح</h5>
                    <p class="card-text">إعادة ضبط برمجة مفاتيحك في حالة الفقدان أو لمنع عمل المفاتيح القديمة.</p>
                </div>
            </div>
        </div>

        <div class="col-lg-4 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">إنشاء مفتاح جديد</h5>
                    <p class="card-text">إنشاء مفاتيح جديدة وإعادة برمجة نظام الأمان الخاص بك في حالة فقدان جميع مفاتيحك.</p>
                </div>
            </div>
        </div>

        <div class="col-lg-4 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">تشخيص المركبات</h5>
                    <p class="card-text">تحليل المشاكل الإلكترونية أو الميكانيكية في مركبتك باستخدام أدوات التشخيص المتقدمة.</p>
                </div>
            </div>
        </div>

        <div class="col-lg-4 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">إصلاح الأقفال</h5>
                    <p class="card-text">إصلاح أو استبدال الأقفال التالفة، بما في ذلك آليات القفل وأسطوانات القفل.</p>
                </div>
            </div>
        </div>

        <div class="col-lg-4 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">مسح الأخطاء</h5>
                    <p class="card-text">خدمات تتعلق بمسح رموز الأخطاء المتعلقة بوسائد الهواء ومرشح الجسيمات الصغيرة وإعادة ضبط وحدة التحكم الإلكترونية.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="cta-section">
        <h2>هل أنتم مستعدون لتأمين مركبتكم؟</h2>
        <p>تواصلوا معنا اليوم للحصول على عرض سعر شخصي!</p>
        <button class="cta-button" onclick=location.href="{% url 'Serrurier:contact' %}">طلب عرض سعر</button>
    </div>
    <div class="certification-section">
        <h2>شهاداتنا وفريقنا</h2>
        <p class="certification-text">
            نحن نفخر بحمل شهادات معترف بها في مجالنا، تؤكد على خبرتنا والتزامنا بتقديم خدمة عالية الجودة. فريقنا يتألف من محترفين مؤهلين وذوي خبرة ملتزمين بتقديم أفضل الخدمات لكم.
        </p>
        <div class="row">
            <div class="col-lg-6">
                <img src="{% static 'images/certif1.jpg' %}" alt="شهادة 1" class="img-fluid certification-image">
                <p>شهادة Apecs</p>
            </div>
            <div class="col-lg-6">
                <img src="{% static 'images/certif2.jpg' %}" alt="شهادة 2" class="img-fluid certification-image">
                <p>شهادة Codificar</p>
            </div>
        </div>
    </div>
</section>

{% endblock %}