Serrurier/urls.py
from django.urls import path
from . import  views
from django.contrib.auth import views as auth_views

app_name = 'Serrurier'

urlpatterns=[
  path('',views.home,name='home'),
  path('change_language/<str:lang>/', views.change_language, name='change_language'),
  # path('mail', views.create_view, name='create_view'),
  path('login/', auth_views.LoginView.as_view(), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('register/', views.register_view, name='register'),
  path('soumettre_avis/', views.soumettre_avis, name='soumettre_avis'),
  path('services/', views.service, name='services'),
  path('contact/', views.contact_view, name='contact'),
  path('admin_contact', views.admin_contact, name='admin_contact'),

  



]

SerurierProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('Serrurier.urls'))
]

Serrurier/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
RATING_CHOICES = [(i, i) for i in range(1, 5)]
class Avis(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    commentaire = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)

    def __str__(self):
        return f'Avis de {self.user}'
    


class Contact(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    message = models.TextField()

    def __str__(self):
        return f"Message from {self.full_name}"

Serrurier/forms.py
from django import forms
from .models import Avis, Contact
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class AvisForm(forms.ModelForm):
    class Meta:
        model = Avis
        fields = ['commentaire', 'rating']


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'email', 'phone_number', 'message']
        widgets = {
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control','rows': 6}),
        }

Serrurier/views.py
from django.shortcuts import redirect, render

from django.http import HttpResponse

from django.shortcuts import render

from datetime import datetime
from Serrurier import models

from Serrurier.models import Avis

from .utils import send_email_with_html_body

from .models import Avis, Contact
from .forms import AvisForm, ContactForm, UserRegisterForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
from django.urls import reverse

class CustomLoginView(LoginView):
    template_name = 'registration/login.html'  


def register_view(request):
    lang = request.session.get('lang', 'fr')
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Envoyer l'email de bienvenue
            subject = "Bienvenue sur Notre Site"
            template = f'mail/welcome_email_{lang}.html'
            context = {
                'date': datetime.today().date(),
                'username': user.username,
                'email': user.email
            }
            receivers = [user.email]
            send_email_with_html_body(
                subjet=subject,
                receivers=receivers,
                template=template,
                context=context
            )
            # Connecter l'utilisateur directement après l'inscription
            login(request, user)
            messages.success(request, 'compte crée avec succès!')
            return redirect('Serrurier:home')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


def contact_view(request):
    lang = request.session.get('lang', 'fr')
    template_name = f"accueil/contact_{lang}.html"

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Vous devez enregistrer le formulaire avant d'envoyer l'email pour avoir accès aux données sauvegardées
            contact = form.save()

            # Envoyer un email de confirmation au client
            subject_client = "Confirmation de réception de votre message"
            template_client = 'mail/confirmation_email_client.html'
            context_client = {
                'full_name': contact.full_name,  # Utilisez l'instance sauvegardée pour récupérer le nom complet
                'date': datetime.today().date(),

            }
            send_email_with_html_body(
                subjet=subject_client,
                receivers=[contact.email],  # Utilisez l'instance sauvegardée pour récupérer l'email
                template=template_client,
                context=context_client
            )

            # Envoyer un email de notification au gérant
            subject_manager = "Nouvelle demande de contact"
            template_manager = 'mail/notification_email_manager.html'
            context_manager = {
                'full_name': contact.full_name,  # Utilisez l'instance sauvegardée pour récupérer les données
                'email': contact.email,
                'phone_number': contact.phone_number,
                'message': contact.message,
                'date': datetime.today().date(),
            }
            send_email_with_html_body(
                subjet=subject_manager,
                receivers=['rochdi53sami@gmail.com'],
                template=template_manager,
                context=context_manager
            )

            messages.success(request, 'Votre demande a été envoyé avec succès!')
            # Rediriger vers une page de succès après l'envoi des emails
            return redirect('Serrurier:home')

    else:
        form = ContactForm()

    return render(request, template_name, {'form': form})


def home(request):
    lang = request.session.get('lang', 'fr')
    avis_list = Avis.objects.all()    
    template_name = f"accueil/home_{lang}.html"
    return render(request, template_name, {'avis_list': avis_list})


def service(request):
    lang = request.session.get('lang', 'fr')
    template_name = f"accueil/services_{lang}.html"

    return render(request,template_name)

@login_required
def soumettre_avis(request):
    lang = request.session.get('lang', 'fr')
    template_name = f"avis/AvisForm_{lang}.html"

    if request.method == 'POST' and request.user.is_authenticated:
        # if avis:  # If an avis already exists
        #     form = AvisForm(request.POST, instance=avis)
        # else:
        form = AvisForm(request.POST)
        
        if form.is_valid():
            avis = form.save(commit=False)
            avis.user = request.user
            avis.save()
            messages.success(request, 'Votre Avis a été envoyé avec succès!')
            return redirect('Serrurier:home')
    else:
        form = AvisForm()
    return render(request, template_name, {'form': form})



def create_view(request, *args, **kwargs):
    """ This view help to create and account for testing sending mails."""
    cxt = {}
    if request.method == "POST":
        email = request.POST.get('email')
        print(email)
        subjet = "Test Email"
        template = 'mail/email.html'
        context = {
            'date': datetime.today().date,
            'email': email
        }

        receivers = [email]

        has_send = send_email_with_html_body(
            subjet=subjet,
            receivers=receivers,
            template=template,
            context=context
            )

        if has_send:
           cxt =  {"msg":"mail envoyee avec success."}
        else:
            cxt = {'msg':'email envoie echoue.'}

    return render(request, 'index.html', cxt)       


@staff_member_required  # Ceci garantit que seul un utilisateur staff (admin) peut accéder à cette vue
def admin_contact(request):
    contacts = Contact.objects.all()  # Récupérer toutes les demandes de contact
    return render(request, 'admin/contact_requests.html', {'contacts': contacts})


def change_language(request, lang):
    request.session['lang'] = lang
    return redirect(request.META.get('HTTP_REFERER', reverse('Serrurier:home')))

Serrurier/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Votre Serrurier</title>

        <!-- Liens vers les fichiers Bootstrap 4.3.1 -->
        <link rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
            crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
        <link rel="stylesheet"
            href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />

        <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/css/flag-icon.min.css" rel="stylesheet">
        
        <!-- Script pour Leaflet -->
        <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
        {% block css %}
        <style>
        .navbar {
            position: fixed;
            top: 0;
            left: 0;
            z-index: 10;
            background-color: #011520; 
            width: 100%;
            overflow: visible;
            transition: transform 1s ease-in-out;
            transform: translateY(-100%); /* Cache initialement la navbar */
            z-index: 3000; 
        }

        .navbar.active {
            transform: translateY(0); /* Affiche la navbar */
        }

        .navbar-brand {
            font-size: 1.5rem;
            font-weight: bold;
            color: #ffffff;
        }

        .navbar-nav {
            margin-top: 0;
        }

        .nav-item {
            margin: 0 1rem;
        }

        .nav-link {
            font-size: 1.2rem;
            color: #ffffff;
        }
        body {
            padding-top: 60px; /* Ajustez cette valeur en fonction de la hauteur de votre barre de navigation */
          }

          .nav-link { color: #92adb6; } /* CSS nav-link color (red) */
          .nav-link:hover { color: #3f5b6c; }
        
          .fixed-bottom-alert {
            position: fixed; /* La position fixe par rapport à la fenêtre du navigateur */
            bottom: 0; /* Positionné en bas */
            left: 25%; /* Aligné à gauche */
            width: 50%; /* Prend toute la largeur */
            z-index: 1050; /* Assurez-vous que cela s'affiche au-dessus des autres éléments */
        }
        .navbar-nav .nav-item {
            display: flex;
            align-items: center;
            height: 100%;
        }
        
        .navbar-nav .nav-link {
            display: flex;
            align-items: center;
            height: 100%;
        }
        
        .flag-icon {
            margin-right: 0.3em;
            vertical-align: middle;
        }
        
    </style>
        {% endblock %}

    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg " id="navbar">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'Serrurier:home' %}">
                        <img src="{% static 'images/Tai_cle_Logo_Vf.png' %}"
                            alt="Logo" class="img-fluid"
                            style="max-height: 60px;">

                        TAI Cles</a>
                    <button class="navbar-toggler" type="button"
                        data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link"
                                    href="{% url 'Serrurier:home' %}">Accueil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"
                                    href="{% url 'Serrurier:services' %}">Services</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"
                                    href="{% url 'Serrurier:contact' %}">Contact</a>
                            </li>
                            
                            {% if user.is_staff or user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link"
                                    href="{% url 'Serrurier:admin_contact' %}">Demandes
                                    de Contact</a>
                            </li>

                            {% endif %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Compte
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navDropdown">
                                    {% if user.is_authenticated %}
                                        <a class="dropdown-item" href="{% url 'Serrurier:logout' %}">Se déconnecter</a>
                                    {% else %}
                                        <a class="dropdown-item" href="{% url 'Serrurier:login' %}">Se connecter</a>
                                        <a class="dropdown-item" href="{% url 'Serrurier:register' %}">S'inscrire</a>
                                    {% endif %}
                                </div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Serrurier:change_language' 'en' %}">
                                    <span class="flag-icon flag-icon-gb"></span> English
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Serrurier:change_language' 'ab' %}">
                                    <span class="flag-icon flag-icon-ma"></span> Arabe
                                </a>
                            </li>
                            
                            

                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid mt-4 mb-5 pl-0 pr-0">
            {% block content %}{% endblock %}
        </div>

        {% if messages %}
		<div class="fixed-bottom-alert">
		{% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
		{% endfor %}
		</div>
	{% endif %}

        <footer
            style="background-color: #011520; color: white; padding: 20px 0;">
            <div style="max-width: 1200px; margin: 0 auto; padding: 0 20px;">
                <div style="display: flex; justify-content: space-between;">
                    <div>
                        <h3>TAI Cles</h3>
                        <p>
                            Hay Salama,
                            Casablanca<br>
                            <a href="{% url 'Serrurier:contact' %}"> Contactez nous</a>
                        </p>
                    </div>
                    <div>
                        <h3>Horaires</h3>
                        <p>
                            Lundi - Samedi : 9h - 17h<br>
                            Dimanche : Fermé
                        </p>
                    </div>
                    <div>
                        <h3>Nous Contacter</h3>
                        <p>

                            <p> 
                                taidiag@hotmail.com <br>
                                +212 6 73 67 67 27</p>
                        </p>
                        
                    </div>
                </div>
            </div>
        </footer>

        <script>
        $(document).ready(function() {
            $("#navbar").addClass("active");
        });
        $(document).ready(function() {
            // Cache initialement la navbar
            var lastScrollTop = 0;
            $(window).scroll(function(event){
               var st = $(this).scrollTop();
               if (st > lastScrollTop){
                   // Faire défiler vers le bas
                   $("#navbar").removeClass("active");
               } else {
                  // Faire défiler vers le haut
                  $("#navbar").addClass("active");
               }
               lastScrollTop = st;
            });
        });
        
    </script>
    </body>
</html>

Serrurier/templates/base_ab.html
{% load static %}
<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>مفاتيحك</title>

    <!-- Liens vers les fichiers Bootstrap 4.3.1 -->
    <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script
        src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <link rel="stylesheet"
        href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/css/flag-icon.min.css" rel="stylesheet">


    <!-- Script pour Leaflet -->
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    {% block css %}
    <style>
        .navbar {
            position: fixed;
            top: 0;
            left: 0;
            z-index: 10;
            background-color: #011520; 
            width: 100%;
            overflow: visible;
            transition: transform 1s ease-in-out;
            transform: translateY(-100%); /* Cache initialement la navbar */
        }

        .navbar.active {
            transform: translateY(0); /* Affiche la navbar */
        }

        .navbar-brand {
            font-size: 1.5rem;
            font-weight: bold;
            color: #ffffff;
        }

        .navbar-nav {
            margin-top: 0;
            margin-right: 0;
        }
        body, .navbar-brand, .nav-link, footer {
            text-align: right;
        }

        .navbar-nav {
            direction: rtl; /* Assure que les éléments de la liste sont affichés de droite à gauche */
        }

        .nav-item {
            margin: 0 1rem;
        }

        .nav-link {
            font-size: 1.2rem;
            color: #ffffff;
        }
        body {
            padding-top: 60px; /* Ajustez cette valeur en fonction de la hauteur de votre barre de navigation */
          }

          .nav-link { color: #92adb6; } /* CSS nav-link color (red) */
          .nav-link:hover { color: #3f5b6c; }
        
          .fixed-bottom-alert {
            position: fixed; /* La position fixe par rapport à la fenêtre du navigateur */
            bottom: 0; /* Positionné en bas */
            left: 25%; /* Aligné à gauche */
            width: 50%; /* Prend toute la largeur */
            z-index: 1050; /* Assurez-vous que cela s'affiche au-dessus des autres éléments */
        }
        .navbar-nav .nav-item {
            display: flex;
            align-items: center;
            height: 100%;
        }
        
        .navbar-nav .nav-link {
            display: flex;
            align-items: center;
            height: 100%;
        }
        
        .flag-icon {
            margin-right: 0.3em;
            vertical-align: middle;
        }
        
    </style>
    {% endblock %}

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg " id="navbar">
            <div class="container">
                <a class="navbar-brand" href="{% url 'Serrurier:home' %}">
                    <img src="{% static 'images/Tai_cle_Logo_Vf.png' %}"
                        alt="Logo" class="img-fluid"
                        style="max-height: 60px;">

                        TAI Cles</a>
                <button class="navbar-toggler" type="button"
                    data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'Serrurier:home' %}">الصفحة الرئيسية</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'Serrurier:services' %}">الخدمات</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'Serrurier:contact' %}">الاتصال</a>
                        </li>
                        
                        {% if user.is_staff or user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link"
                                href="{% url 'Serrurier:admin_contact' %}">طلبات الاتصال</a>
                        </li>
                        {% endif %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                الحساب
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navDropdown">
                                {% if user.is_authenticated %}
                                    <a class="dropdown-item" href="{% url 'Serrurier:logout' %}">تسجيل الخروج</a>
                                {% else %}
                                    <a class="dropdown-item" href="{% url 'Serrurier:login' %}">تسجيل الدخول</a>
                                    <a class="dropdown-item" href="{% url 'Serrurier:register' %}">تسجيل</a>
                                {% endif %}
                            </div>
                        </li>
                        
                        <li class="nav-item">
                            <a href="{% url 'Serrurier:change_language' 'fr' %}">
                                <span class="flag-icon flag-icon-fr"></span> الفرنسية
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'Serrurier:change_language' 'en' %}">
                                <span class="flag-icon flag-icon-gb"></span> الإنجليزية
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container-fluid mt-4 mb-5 pl-0 pr-0">
        {% block content %}{% endblock %}
    </div>

    {% if messages %}
    <div class="fixed-bottom-alert">
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
    </div>
    {% endif %}

    <footer
        style="background-color: #011520; color: white; padding: 20px 0;text-align: right;">
        <div style="max-width: 1200px; margin: 0 auto; padding: 0 20px;">
            <div style="display: flex; justify-content: space-between;">
                <div>
                    <h3>TAI Cles</h3>
                    <p>
                        هاي سلامة،
                        الدار البيضاء<br>
                        <a href="{% url 'Serrurier:contact' %}"> اتصل بنا</a>
                    </p>
                </div>
                <div>
                    <h3>ساعات العمل</h3>
                    <p>
                        الإثنين - السبت: 9 صباحًا - 5 مساءً<br>
                        الأحد: مغلق
                    </p>
                </div>
                <div>
                    <h3>اتصل بنا</h3>
                    <p>
                        <p> 
                            taidiag@hotmail.com <br>
                            +212 6 73 67 67 27</p>
                    </p>
                    
                </div>
            </div>
        </div>
    </footer>

    <script>
    $(document).ready(function() {
        $("#navbar").addClass("active");
    });
    $(document).ready(function() {
        // Cache initialement la navbar
        var lastScrollTop = 0;
        $(window).scroll(function(event){
           var st = $(this).scrollTop();
           if (st > lastScrollTop){
               // Faire défiler vers le bas
               $("#navbar").removeClass("active");
           } else {
              // Faire défiler vers le haut
              $("#navbar").addClass("active");
           }
           lastScrollTop = st;
        });
    });
    </script>
</body>
</html>

Serrurier/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1> Bienvenu sur Email testing avec django </h1>

    {% if msg %}
        <h4> {{ msg }}</h4>
    {% endif %}    
    
    <form action="" method="post">
        {% csrf_token %}
        <label for="email"></label>
        <input id="email" name="email" type="email" placeholder="Enter your email address">
        <button type="submit"> Envoyez </button>
    </form>
</body>
</html>